### ISSUE TITLE
CSS Modules Design

### ISSUE THREAD

**Issue by miniflycn** [miniflycn/note#32]
> 这个方案否决，组件对外部隔离，外部不对组件隔离
# 全局配置（项目全局配置）
### normalize

> 抹平浏览器差异，可受限区域，具体看局部上的例子
### 变量

``` css
:root {
  --brand-color: blue;
}
.my-component {
  background-color: var(--brand-color);
}
```

``` css
import './color.css'

.my-component {
  background-color: var(--brand-color);
}
```
# 组件内（组件内机制）
### 隔离机制
- CSS

``` css
:host {
  .my-component {
     background: #fff;
  }
}
```
- JSX:

``` js
import React, { Component } from 'react'
import  { host } './index.css' // host should be: hash(relativePath)

class MyComponent extends Component {
  render() {
    return (<div host={host}>
        <div className="my-component">hello world</div>
    </div>)
  }
}
```
- compile:

``` css
[host=hash(relativePath)] .my-component {
  background: #fff;
}
```
### normalize

``` css
:host {
  composes * from './normalize.css'
}
```
### hash(relativePath)
- relativePath = 相对 Current Working Directory 的文件路径
- 所以`hash(relativePath)`对于单一项目是单一值
# 覆盖（可控范围补丁）
### 组件覆盖
- 手动覆盖

``` css
[host=hash(relativePath)] .my-component {
  background: #000;
}
```
- 语法糖

``` css
:host(../my-component/main.css) {
  .my-component {
    background: #000;
  }
}
```
